
-- Create banners table
CREATE TABLE IF NOT EXISTS public.banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    title TEXT,
    link_url TEXT,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Active RLS
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.banners FOR SELECT USING (true);

-- Allow authenticated (admin) access for everything
-- Note: Replace with proper admin check if needed, 
-- but for simplicity assuming admin uses same anon key 
-- and we control logic via AdminDhevv.tsx
CREATE POLICY "Allow individual insert" ON public.banners FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow individual update" ON public.banners FOR UPDATE USING (true);
CREATE POLICY "Allow individual delete" ON public.banners FOR DELETE USING (true);
