-- Create the Product Prices table
CREATE TABLE IF NOT EXISTS "Product Prices" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_name TEXT NOT NULL,
  variant_type TEXT NOT NULL,
  duration TEXT NOT NULL,
  price BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(app_name, variant_type, duration)
);

-- Insert default data
INSERT INTO "Product Prices" (app_name, variant_type, duration, price) VALUES
('NETFLIX', 'Sharing 2 User', '1 Day', 8000),
('NETFLIX', 'Sharing 2 User', '1 Week', 17000),
('NETFLIX', 'Sharing 1 User', '1 Day', 10000),
('NETFLIX', 'Sharing 1 User', '1 Week', 20000),
('NETFLIX', 'Private', '1 Month', 150000),
('VIDIO', 'Sharing 2 User (Mobile Only)', '1 Month', 22000),
('VIDIO', 'Private Mobile (No Sharing)', '1 Month', 31000),
('VIDIO', 'Sharing 2 User (All Device)', '1 Month', 28000),
('VIDIO', 'Private (TV Only)', '1 Year', 15000),
('PRIME VIDEO', 'Sharing', '1 Month', 10000),
('PRIME VIDEO', 'Private', '1 Month', 20000),
('AMAZON PRIME', 'Sharing', '1 Month', 8000),
('AMAZON PRIME', 'Private', '1 Month', 15000),
('WETV', 'Sharing 6 User', '1 Month', 12000),
('VIU PREMIUM (PRIVATE)', 'Anti Limit', '1 Month', 2000),
('VIU PREMIUM (PRIVATE)', 'Anti Limit', '3 Month', 3000),
('VIU PREMIUM (PRIVATE)', 'Anti Limit', '6 Month', 3500),
('VIU PREMIUM (PRIVATE)', 'Anti Limit', '1 Year', 5000),
('iQIYI', 'Sharing (Standard)', '1 Month', 8000),
('iQIYI', 'Sharing (Premium)', '1 Month', 10000),
('iQIYI', 'Sharing', '3 Month', 13000),
('HBO MAX', 'Sharing', '1 Month', 10000),
('DRAMA BOX', 'Standard', '1 Month', 9000),
('MOVIE BOX', 'Standard', '1 Month', 10000),
('BStation', 'Sharing', '1 Month', 7500),
('BStation', 'Sharing', '1 Year', 20000),
('LOKLOK', 'Basic Sharing 3 User', '1 Month', 22000),
('SPOTIFY STUDENT', 'Standard', '1 Month', 12000),
('SPOTIFY STUDENT', 'Bergaransi', '1 Month', 20000),
('SPOTIFY STUDENT', 'Tanpa Garansi', '3 Month', 32000),
('APPLE MUSIC', 'Via imessage', '1 Month', 13000),
('YOUTUBE', 'Family Plan', '1 Month', 6000),
('YOUTUBE', 'Individu Plan', '1 Month', 10000),
('CANVA', 'Member Premium (Invite Link)', '1 Month', 5000),
('CANVA', 'Member Premium (Invite Link)', '6 Month', 12000),
('CANVA', 'Head/Owner (Invite 100 Member)', 'Lifetime/Account', 10000),
('CAPCUT', 'Pro (Anti BackFree)', '5 Month', 42000),
('CAPCUT', 'Pro (Anti BackFree)', '35 Day', 15000),
('CAPCUT', 'Pro (Anti BackFree)', '28 Day', 10000),
('CAPCUT', 'Pro (Anti BackFree)', '21 Day', 8000),
('ALIGHT MOTION', 'Private', '1 Year', 5000),
('IBIS PAINT X', 'Sharing', '12 Month', 15000),
('MEITU', 'Sharing', '1 Month', 15000),
('WATTPAD', 'Sharing', '12 Month', 12000),
('FIZZO NOVEL', 'Sharing', '1 Month', 8000),
('CHATGPT+', 'Sharing Via Invite', '1 Month', 14000),
('CHATGPT+', 'Private (Tanpa Garansi)', '1 Month', 20000),
('CHATGPT+', 'Private (Full Garansi)', '1 Month', 25000),
('CHATGPT+', 'Head (Tanpa Garansi)', '1 Month', 18000),
('CHATGPT+', 'Head (Full Garansi)', '1 Month', 23000),
('ZOOM PRO', 'Pro', '30 Day', 12000),
('PICSART', 'Private', '1 Month', 10000);

-- Enable RLS and add policies
ALTER TABLE "Product Prices" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "Product Prices"
  FOR SELECT USING (true);

CREATE POLICY "Enable update for all users" ON "Product Prices"
  FOR UPDATE USING (true);
